# Generated by Django 3.0.6 on 2020-06-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('contacts', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
