# Generated by Django 3.0.6 on 2020-06-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='listing',
        ),
    ]
